/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_PERCENT_EQ_EQ = 1,
  anon_sym_PERCENT_GT = 2,
  anon_sym_LT_PERCENT_EQ = 3,
  anon_sym_LT_PERCENT = 4,
  anon_sym_LT_PERCENT_POUND = 5,
  sym__block_body = 6,
  sym_line_content = 7,
  sym_content = 8,
  sym__line_code_start = 9,
  sym__line_output_raw_start = 10,
  sym__line_output_start = 11,
  sym__line_comment_start = 12,
  sym__line_end = 13,
  sym_template = 14,
  sym_block_output_raw = 15,
  sym_block_output = 16,
  sym_block_code = 17,
  sym_block_comment = 18,
  sym_line_output_raw = 19,
  sym_line_output = 20,
  sym_line_code = 21,
  sym_line_comment = 22,
  aux_sym_template_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_PERCENT_EQ_EQ] = "<%==",
  [anon_sym_PERCENT_GT] = "%>",
  [anon_sym_LT_PERCENT_EQ] = "<%=",
  [anon_sym_LT_PERCENT] = "<%",
  [anon_sym_LT_PERCENT_POUND] = "<%#",
  [sym__block_body] = "_block_body",
  [sym_line_content] = "line_content",
  [sym_content] = "content",
  [sym__line_code_start] = "_line_code_start",
  [sym__line_output_raw_start] = "_line_output_raw_start",
  [sym__line_output_start] = "_line_output_start",
  [sym__line_comment_start] = "_line_comment_start",
  [sym__line_end] = "_line_end",
  [sym_template] = "template",
  [sym_block_output_raw] = "block_output_raw",
  [sym_block_output] = "block_output",
  [sym_block_code] = "block_code",
  [sym_block_comment] = "block_comment",
  [sym_line_output_raw] = "line_output_raw",
  [sym_line_output] = "line_output",
  [sym_line_code] = "line_code",
  [sym_line_comment] = "line_comment",
  [aux_sym_template_repeat1] = "template_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_PERCENT_EQ_EQ] = anon_sym_LT_PERCENT_EQ_EQ,
  [anon_sym_PERCENT_GT] = anon_sym_PERCENT_GT,
  [anon_sym_LT_PERCENT_EQ] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT] = anon_sym_LT_PERCENT,
  [anon_sym_LT_PERCENT_POUND] = anon_sym_LT_PERCENT_POUND,
  [sym__block_body] = sym__block_body,
  [sym_line_content] = sym_line_content,
  [sym_content] = sym_content,
  [sym__line_code_start] = sym__line_code_start,
  [sym__line_output_raw_start] = sym__line_output_raw_start,
  [sym__line_output_start] = sym__line_output_start,
  [sym__line_comment_start] = sym__line_comment_start,
  [sym__line_end] = sym__line_end,
  [sym_template] = sym_template,
  [sym_block_output_raw] = sym_block_output_raw,
  [sym_block_output] = sym_block_output,
  [sym_block_code] = sym_block_code,
  [sym_block_comment] = sym_block_comment,
  [sym_line_output_raw] = sym_line_output_raw,
  [sym_line_output] = sym_line_output,
  [sym_line_code] = sym_line_code,
  [sym_line_comment] = sym_line_comment,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_PERCENT_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym__block_body] = {
    .visible = false,
    .named = true,
  },
  [sym_line_content] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym__line_code_start] = {
    .visible = false,
    .named = true,
  },
  [sym__line_output_raw_start] = {
    .visible = false,
    .named = true,
  },
  [sym__line_output_start] = {
    .visible = false,
    .named = true,
  },
  [sym__line_comment_start] = {
    .visible = false,
    .named = true,
  },
  [sym__line_end] = {
    .visible = false,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_block_output_raw] = {
    .visible = true,
    .named = true,
  },
  [sym_block_output] = {
    .visible = true,
    .named = true,
  },
  [sym_block_code] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_output_raw] = {
    .visible = true,
    .named = true,
  },
  [sym_line_output] = {
    .visible = true,
    .named = true,
  },
  [sym_line_code] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == '<') ADVANCE(1);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(4);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(9);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(13);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ);
      if (lookahead == '=') ADVANCE(8);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_POUND);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__block_body);
      if (lookahead == '%') ADVANCE(6);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_line_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 5, .external_lex_state = 3},
  [21] = {.lex_state = 5, .external_lex_state = 3},
  [22] = {.lex_state = 5, .external_lex_state = 3},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 5, .external_lex_state = 3},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 3},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_GT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(1),
    [sym_content] = ACTIONS(1),
    [sym__line_code_start] = ACTIONS(1),
    [sym__line_output_raw_start] = ACTIONS(1),
    [sym__line_output_start] = ACTIONS(1),
    [sym__line_comment_start] = ACTIONS(1),
    [sym__line_end] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(35),
    [sym_block_output_raw] = STATE(3),
    [sym_block_output] = STATE(3),
    [sym_block_code] = STATE(3),
    [sym_block_comment] = STATE(3),
    [sym_line_output_raw] = STATE(3),
    [sym_line_output] = STATE(3),
    [sym_line_code] = STATE(3),
    [sym_line_comment] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(5),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(7),
    [anon_sym_LT_PERCENT] = ACTIONS(9),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(11),
    [sym_content] = ACTIONS(13),
    [sym__line_code_start] = ACTIONS(15),
    [sym__line_output_raw_start] = ACTIONS(17),
    [sym__line_output_start] = ACTIONS(19),
    [sym__line_comment_start] = ACTIONS(21),
  },
  [STATE(2)] = {
    [sym_block_output_raw] = STATE(2),
    [sym_block_output] = STATE(2),
    [sym_block_code] = STATE(2),
    [sym_block_comment] = STATE(2),
    [sym_line_output_raw] = STATE(2),
    [sym_line_output] = STATE(2),
    [sym_line_code] = STATE(2),
    [sym_line_comment] = STATE(2),
    [aux_sym_template_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(25),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(28),
    [anon_sym_LT_PERCENT] = ACTIONS(31),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(34),
    [sym_content] = ACTIONS(37),
    [sym__line_code_start] = ACTIONS(40),
    [sym__line_output_raw_start] = ACTIONS(43),
    [sym__line_output_start] = ACTIONS(46),
    [sym__line_comment_start] = ACTIONS(49),
  },
  [STATE(3)] = {
    [sym_block_output_raw] = STATE(2),
    [sym_block_output] = STATE(2),
    [sym_block_code] = STATE(2),
    [sym_block_comment] = STATE(2),
    [sym_line_output_raw] = STATE(2),
    [sym_line_output] = STATE(2),
    [sym_line_code] = STATE(2),
    [sym_line_comment] = STATE(2),
    [aux_sym_template_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(52),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(5),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(7),
    [anon_sym_LT_PERCENT] = ACTIONS(9),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(11),
    [sym_content] = ACTIONS(54),
    [sym__line_code_start] = ACTIONS(15),
    [sym__line_output_raw_start] = ACTIONS(17),
    [sym__line_output_start] = ACTIONS(19),
    [sym__line_comment_start] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(58), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(56), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [15] = 2,
    ACTIONS(62), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(60), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [30] = 2,
    ACTIONS(66), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(64), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [45] = 2,
    ACTIONS(70), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(68), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [60] = 2,
    ACTIONS(74), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(72), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [75] = 2,
    ACTIONS(78), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(76), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [90] = 2,
    ACTIONS(82), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(80), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [105] = 2,
    ACTIONS(86), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(84), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [120] = 2,
    ACTIONS(90), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(88), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [135] = 2,
    ACTIONS(94), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(92), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [150] = 2,
    ACTIONS(98), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(96), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [165] = 2,
    ACTIONS(102), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(100), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [180] = 2,
    ACTIONS(106), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(104), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [195] = 2,
    ACTIONS(110), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(108), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [210] = 2,
    ACTIONS(114), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(112), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [225] = 2,
    ACTIONS(118), 2,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
    ACTIONS(116), 8,
      sym_content,
      sym__line_code_start,
      sym__line_output_raw_start,
      sym__line_output_start,
      sym__line_comment_start,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
  [240] = 2,
    ACTIONS(120), 1,
      sym_line_content,
    ACTIONS(122), 1,
      sym__line_end,
  [247] = 2,
    ACTIONS(124), 1,
      sym_line_content,
    ACTIONS(126), 1,
      sym__line_end,
  [254] = 2,
    ACTIONS(128), 1,
      sym_line_content,
    ACTIONS(130), 1,
      sym__line_end,
  [261] = 2,
    ACTIONS(132), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(134), 1,
      sym__block_body,
  [268] = 2,
    ACTIONS(136), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(138), 1,
      sym__block_body,
  [275] = 2,
    ACTIONS(140), 1,
      sym_line_content,
    ACTIONS(142), 1,
      sym__line_end,
  [282] = 2,
    ACTIONS(144), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(146), 1,
      sym__block_body,
  [289] = 2,
    ACTIONS(148), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(150), 1,
      sym__block_body,
  [296] = 1,
    ACTIONS(152), 1,
      sym__line_end,
  [300] = 1,
    ACTIONS(154), 1,
      anon_sym_PERCENT_GT,
  [304] = 1,
    ACTIONS(156), 1,
      sym__line_end,
  [308] = 1,
    ACTIONS(158), 1,
      anon_sym_PERCENT_GT,
  [312] = 1,
    ACTIONS(160), 1,
      anon_sym_PERCENT_GT,
  [316] = 1,
    ACTIONS(162), 1,
      sym__line_end,
  [320] = 1,
    ACTIONS(164), 1,
      sym__line_end,
  [324] = 1,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
  [328] = 1,
    ACTIONS(168), 1,
      anon_sym_PERCENT_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 15,
  [SMALL_STATE(6)] = 30,
  [SMALL_STATE(7)] = 45,
  [SMALL_STATE(8)] = 60,
  [SMALL_STATE(9)] = 75,
  [SMALL_STATE(10)] = 90,
  [SMALL_STATE(11)] = 105,
  [SMALL_STATE(12)] = 120,
  [SMALL_STATE(13)] = 135,
  [SMALL_STATE(14)] = 150,
  [SMALL_STATE(15)] = 165,
  [SMALL_STATE(16)] = 180,
  [SMALL_STATE(17)] = 195,
  [SMALL_STATE(18)] = 210,
  [SMALL_STATE(19)] = 225,
  [SMALL_STATE(20)] = 240,
  [SMALL_STATE(21)] = 247,
  [SMALL_STATE(22)] = 254,
  [SMALL_STATE(23)] = 261,
  [SMALL_STATE(24)] = 268,
  [SMALL_STATE(25)] = 275,
  [SMALL_STATE(26)] = 282,
  [SMALL_STATE(27)] = 289,
  [SMALL_STATE(28)] = 296,
  [SMALL_STATE(29)] = 300,
  [SMALL_STATE(30)] = 304,
  [SMALL_STATE(31)] = 308,
  [SMALL_STATE(32)] = 312,
  [SMALL_STATE(33)] = 316,
  [SMALL_STATE(34)] = 320,
  [SMALL_STATE(35)] = 324,
  [SMALL_STATE(36)] = 328,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_code, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_code, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_output_raw, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_output_raw, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_output, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_output, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_comment, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_output_raw, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_output_raw, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_output, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_output, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_code, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_code, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_code, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_code, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_output_raw, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_output_raw, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_output, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_output, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_comment, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_output_raw, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_output_raw, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_output, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_output, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_code, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_code, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [166] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_content = 0,
  ts_external_token__line_code_start = 1,
  ts_external_token__line_output_raw_start = 2,
  ts_external_token__line_output_start = 3,
  ts_external_token__line_comment_start = 4,
  ts_external_token__line_end = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_content] = sym_content,
  [ts_external_token__line_code_start] = sym__line_code_start,
  [ts_external_token__line_output_raw_start] = sym__line_output_raw_start,
  [ts_external_token__line_output_start] = sym__line_output_start,
  [ts_external_token__line_comment_start] = sym__line_comment_start,
  [ts_external_token__line_end] = sym__line_end,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_content] = true,
    [ts_external_token__line_code_start] = true,
    [ts_external_token__line_output_raw_start] = true,
    [ts_external_token__line_output_start] = true,
    [ts_external_token__line_comment_start] = true,
    [ts_external_token__line_end] = true,
  },
  [2] = {
    [ts_external_token_content] = true,
    [ts_external_token__line_code_start] = true,
    [ts_external_token__line_output_raw_start] = true,
    [ts_external_token__line_output_start] = true,
    [ts_external_token__line_comment_start] = true,
  },
  [3] = {
    [ts_external_token__line_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_mojolicious_external_scanner_create(void);
void tree_sitter_mojolicious_external_scanner_destroy(void *);
bool tree_sitter_mojolicious_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_mojolicious_external_scanner_serialize(void *, char *);
void tree_sitter_mojolicious_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mojolicious(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_mojolicious_external_scanner_create,
      tree_sitter_mojolicious_external_scanner_destroy,
      tree_sitter_mojolicious_external_scanner_scan,
      tree_sitter_mojolicious_external_scanner_serialize,
      tree_sitter_mojolicious_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
